### ISSUE TITLE
Inconsistency in server status messages

### ISSUE THREAD

**Issue by fabiobosisio** [Freechains/README#8]
If we try to create a server in a place on the disk that our user does not have permission to write, the daemon accepts and does not give an error, it also allows us to create the shared key, but when trying to make a joint it says that the chain is empty. If we try to create in a place that the user has permission, even if we don't have the directory, it creates without problems and works perfectly. It is a matter of permission, but it should give error when starting the server, for some reason it ignores it even though it does not have permission to create the folder on the disk.

**Comment by fsantanna** [comment]
Reproducing the bug:

```
> freechains-host start / &    <-- no permission to write in `/`
> freechains chains join '$chat' 96700ACD1128035FFEF5DC264DF87D5FEE45FF15E2A880708AE40675C9AD039E
! chain does not exist
```
